GET https://roller-revamp.web.app/dashboard HTTP/1.1
content-type: application/json

{"apples" : "Many Apples",
"cookies":
{
  "session": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImJlYmYxMDBlYWRkYTMzMmVjOGZlYTU3ZjliNWJjM2E2YWIyOWY1NTUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcm9sbGVyLXJldmFtcCIsImF1ZCI6InJvbGxlci1yZXZhbXAiLCJhdXRoX3RpbWUiOjE2NTIwMzM5NzEsInVzZXJfaWQiOiI1b1hadjNPZFdqTTBzZEkyZUk2VzA2bzNDOEoyIiwic3ViIjoiNW9YWnYzT2RXak0wc2RJMmVJNlcwNm8zQzhKMiIsImlhdCI6MTY1MjAzMzk3MSwiZXhwIjoxNjUyMDM3NTcxLCJlbWFpbCI6InRlc3Q0QHRlc3QuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3Q0QHRlc3QuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.PUxK5HhHu31ilIsauwJegDLGuQyR85rpN9XXTy9iN_PYWOlhFXmn6j9dDmqRIxZ6O2AwEwsalmVqBC-zlHMiJSwSlDTgAYLj_LyE7yp-YQgHTJBhZ_Mi4IEslI4tGal1faIjO9fIvUJKOQq9iDlzihvJE3t0pttnieDID2Gi-Kz5i5YeXhx7quB5wJJcQ-WFPc304dr77Ak9AWsfWbW84QHUUA5xgMlXOEzu1mjf72pc2yNxIRjwaeI3Ad2BNfa5dTy85kXxNUl-wun2Mhjy-FkMZcAkdATjen3Mr0nFEO8ungir77o1ICbaCYzbzfP4q-5k_MdZWqFZA8mkp6DNQw"
}
}
#GET http://localhost:4000/ HTTP/1.1
